### PR TITLE
Add StringSearchMode to findNodes operation

### PR DESCRIPTION
**Pull request by ghost**
Added a new operation to Neo4jGraphAPI allowing to find Nodes with a Label and a String property matching a given Template, using EXACT, PREFIX, SUFFIX or CONTAINS mode.

See also: https://issues.apache.org/jira/browse/TINKERPOP-2133

### CODE REVIEW

**Comment by jexp** [comment]
Hi @skorikov thanks a lot for your contribution.
are those operations then also used in gremlin-neo4j?

It would be great if you can limit the changes to the bits that are required for the issue.

It would also be necessary to sign our CLA esp. for neo4j-tinkerpop-api-impl
https://neo4j.com/developer/cla/

Thanks alot.

**Comment by ghost** [comment]
Hi @jexp, thank you for your help!
I limited the changed to the required minimum and updated the pull request.
I also submitted the Neo4j CLA.

These changes in the API (and the implementation - https://github.com/neo4j-contrib/neo4j-tinkerpop-api-impl/pull/11/files) are required to implement the changes in gremlin-neo4j. However, in order to update gremlin-neo4j we would need to reference a new version of the internal neo4j API (0.1 -> 0.1.1). Updating all three modules at once (gremlin-neo4j, neo4j-tinkerpop-api and neo4j-tinkerpop-api-impl) seems a bit risky to mee... Perhaps you can provide some guidance on how to proceed with this?

**Comment by jexp** [comment]
Ok, sgtm. I try to do both releases today.

**Comment by jexp** [comment]
I'd also love to hear about your use of Neo4j + TP3, perhaps offline, if you drop me an email to michael at neo4j.com

**Comment by jexp** [comment]
Released both projects to maven central, might take a bit until they show up.
Let me know when you updated gremlin-neo4j.

**Comment by ghost** [comment]
@jexp Cool! :smiley: I implemented the change in gremlin-neo4j, but would prefer to wait till the new API versions are available in maven central before submitting a pull request - otherwise the build would fail due to missing dependencies...

**Pull request merged**
